-- |
-- Module      : Clementine.AST
-- Copyright   : (c) 2026 Clementine contributors
-- License     : GPL v3 (see LICENSE)
--
-- Surface AST for the Clementine high-level protocol language.
--
-- This module defines the datatypes that the parser produces and the
-- lowering pass consumes. Source positions are attached to every
-- "interesting" node so that error messages and the planned source-map
-- sidecar can point at the right location in the original .clem file.
--
-- Reference: design steps 1 and 3 in the Clementine notes.
module Clementine.AST where

import Data.Text (Text)

-- | Source position. We carry our own type rather than reuse parsec's
-- 'SourcePos' so we are not coupled to a particular parser library;
-- the parser converts at the boundary.
data SrcPos = SrcPos
  { spFile :: !FilePath
  , spLine :: !Int
  , spCol  :: !Int
  } deriving (Eq, Show)

-- | A whole protocol declaration.
data Protocol = Protocol
  { protoName       :: !Text
  , protoBuiltins   :: ![Builtin]
  , protoPrincipals :: ![Principal]
  , protoSteps      :: ![Step]
  , protoVerify     :: ![Query]
  , protoPos        :: !SrcPos
  } deriving (Show)

-- | Cryptographic primitive theory the protocol depends on. Each one
-- maps to a Tamarin builtin in 'Clementine.Lower'.
data Builtin
  = BIDH
  | BISigning
  | BIHashing
  | BISymEnc
  | BIAsymEnc
  deriving (Eq, Show)

-- | A principal declaration.
data Principal = Principal
  { prinName  :: !Text
  , prinKnows :: ![Knowledge]
  , prinPos   :: !SrcPos
  } deriving (Show)

-- | A single knowledge item inside a 'principal' block.
data Knowledge
  = -- | @generates skA@ — fresh long-term value generated by this principal.
    KGenerates !Text !SrcPos
  | -- | @knows public p@ or @knows public p = expr@.
    KKnowsPublic !Text !(Maybe Expr) !SrcPos
  | -- | @knows private psk@ — pre-shared symmetric key, never published.
    KKnowsPrivate !Text !SrcPos
  deriving (Show)

-- | A protocol step. The 'stepKind' field distinguishes a network step
-- (which has a sender and a receiver, plus a channel kind) from a
-- @local@ step (computation only, no wire traffic).
data Step = Step
  { stepLabel :: !Text
  , stepFrom  :: !Text
  , stepKind  :: !StepKind
  , stepBody  :: ![StepStmt]
  , stepPos   :: !SrcPos
  } deriving (Show)

data StepKind
  = -- | A network step from one principal to another.
    StepNetwork !Text !ChannelKind
  | -- | A local computation step (no @send@).
    StepLocal
  deriving (Show)

-- | The four channel arrows from design step 1.
data ChannelKind
  = ChNet      -- ^ @->@: public network (Dolev-Yao)
  | ChAuth     -- ^ @~>@: authentic only
  | ChConf     -- ^ @=>@: confidential only
  | ChSecure   -- ^ @:>@: TLS-record style
  deriving (Eq, Show)

-- | A statement inside a step body.
data StepStmt
  = -- | @new x@: introduce a fresh nonce in this step's scope.
    SNew     !Text !SrcPos
  | -- | @let v = e@: bind a name to a (pure) expression.
    SLet     !Text !Expr !SrcPos
  | -- | @require e@: a precondition; compiles to an Eq-restriction.
    SRequire !Expr !SrcPos
  | -- | @send e@: emit on the wire (only in network steps).
    SSend    !Expr !SrcPos
  | -- | @claim secret(v)@: anchor for a secrecy lemma.
    SClaim   !Claim !SrcPos
  deriving (Show)

-- | The kinds of inline claims a step can make. v0.0 supports only
-- secrecy; agreement and authentication claims are derived from the
-- 'verify' block instead.
data Claim
  = ClaimSecret !Text
  deriving (Show)

-- | Surface expressions. We keep this small and grow it as the parser
-- and lowerer learn more constructs.
data Expr
  = -- | A bare identifier — variable, parameter, or principal name.
    EVar   !Text !SrcPos
  | -- | A single-quoted public constant, e.g. @\'g\'@.
    EConst !Text !SrcPos
  | -- | An n-ary tuple @<e1, ..., en>@.
    ETup   ![Expr] !SrcPos
  | -- | A primitive operator application: @AENC(m, k)@, @SIGN(sk, m)@, etc.
    EApp   !PrimOp ![Expr] !SrcPos
  | -- | DH exponentiation, written infix in surface syntax: @e ^ e@.
    EExp   !Expr !Expr !SrcPos
  deriving (Show)

-- | The cryptographic primitive operators recognised in step bodies.
data PrimOp
  = OpEnc | OpDec
  | OpAEnc | OpADec
  | OpPK
  | OpSign | OpVerify
  | OpH
  | OpMAC
  deriving (Eq, Show)

-- | A query in the @verify@ block. Each one corresponds to a lemma
-- template from design step 2 §2.3.
data Query
  = -- | @executable@: at least one full honest run exists.
    QExecutable !SrcPos
  | -- | @secrecy(t)@.
    QSecrecy !TermRef !SrcPos
  | -- | @forward_secrecy(t)@ — temporal-form FS lemma (no phase needed).
    QForwardSecrecy !TermRef !SrcPos
  | -- | @injective_agreement(I, R, [ts...])@.
    QInjAgreement !Text !Text ![TermRef] !SrcPos
  | -- | @non_injective_agreement(I, R, [ts...])@.
    QNonInjAgreement !Text !Text ![TermRef] !SrcPos
  | -- | @authentication(I, R)@ — Lowe's aliveness.
    QAuthentication !Text !Text !SrcPos
  deriving (Show)

-- | A reference to a term inside the @verify@ block. Per design step
-- 1 §1.4 we allow three forms: bare @v@, @step.v@, @principal\@step.v@.
-- For v0.0 only the bare form is supported and ambiguity is rejected
-- by name resolution.
data TermRef = TermRef
  { trPrincipal :: !(Maybe Text)
  , trStep      :: !(Maybe Text)
  , trVar       :: !Text
  , trPos       :: !SrcPos
  } deriving (Show)
